# Generated by Django 4.2.7 on 2024-02-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_bio_remove_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
    ]
