# Generated by Django 4.2.7 on 2024-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('level-1', 'level-1'), ('level-2', 'level-2'), ('level-3', 'level-3'), ('level-4', 'level-4')], default='level-1', max_length=225),
        ),
    ]
