# Generated by Django 4.2.7 on 2024-02-03 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Quiz Categories'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='ex_file',
            field=models.FileField(null=True, upload_to='quiz/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult'), ('Professional', 'Professional')], default='Easy', max_length=225, null=True),
        ),
    ]
